### ISSUE TITLE
Logic Issue in MenuSystem.lua

### ISSUE THREAD

**Issue by saywaking** [XboxUnity/AuroraScripts#5]
Small issue

line 24 
you check  "if ret.Canceled == true" after "if ret.Canceled == true"
any reason for that?

**Comment by Swizzy** [comment]
Not sure how this is a "issue", it doesn't do any harm, it doesn't do anything actually...

And no, you're right, it's meaningless... it's just something that happened while i was writing that... it doesn't change anything if you remove that second if...

**Comment by saywaking** [comment]
there are many channels to "tell" you something -> forums, github, mailing, pull requesting etc.
i couldn't decide, which one to use. I actually don't want to have that many pull request, when you are able to push directly :)
Let's see how it will continue.
